config/routes.rb
Rails.application.routes.draw do
  root 'phones#select_phone'
  get 'select_phone'          => 'phones#select_phone',          as: :select_phone
  get 'get_models_for_select' => 'phones#get_models_for_select', as: :get_models_for_select
  get 'get_phone_info'        => 'phones#get_phone_info',        as: :get_phone_info
  get 'search_phone'          => 'phones#search_phone',          as: :search_phone
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  
  # respond_to :html, :js

  def select_phone
    @brands = get_brands
    @brand_models = []
  end

  def get_models_for_select
    @brand_models = []
    brand_page = params[:brand_page]
    if brand_page
      page = Nokogiri::HTML(open("http://www.gsmarena.com/#{brand_page}"))
      page.css('.makers li').each do |model_info|
        @brand_models << [model_info.css('span').text.capitalize,
                          model_info.css('a').attr('href').text]
      end
    end
    respond_to do |format|
      format.js
    end
  end

  def get_phone_info
    @categories = []
    @titles = []
    @info = []
    phone_page = params[:phone_page]
    if phone_page
      page = Nokogiri::HTML(open("http://www.gsmarena.com/#{phone_page}"))
      page.css('table').each do |table|
        @categories << table.css('th').text
        
        titles = []
        table.css('.ttl').each do |title|
          titles << title.text
        end
        @titles << titles

        info = []
        table.css('.nfo').each do |i|
          info << i.text
        end
        @info << info
      end
    end
    # puts "***********************************"
    # puts @categories.inspect
    # puts @titles.inspect
    # puts @info.inspect
    # puts "***********************************"
    respond_to do |format|
      format.js
    end
  end

  def search_phone
    @phones = []
    query = params[:query]

    agent = Mechanize.new
    agent.get('http://www.gsmarena.com')
    search_form = agent.page.forms.first
    search_form.sName = query
    search_form.submit
    page = page = Nokogiri::HTML(open(agent.page.uri.to_s))

    page.css('.makers li').each do |phone_info|
      @phones << [phone_info.css('span').text.capitalize,
                  "http://www.gsmarena.com/#{phone_info.css('a').attr('href').text}",
                  phone_info.css('img').attr('src').text]
    end
    # puts "***********************************"
    # puts @phones.inspect
    # puts @phones.count
    # puts "***********************************"
    respond_to do |format|
      format.js
    end
  end

  private

  def get_brands
    brands = []
    page = Nokogiri::HTML(open("http://www.gsmarena.com/makers.php3"))
    page.css('.st-text td').each do |brand_info|
      brands << [brand_info.text.gsub(/[0-9]/, '').gsub(/\s.+/, '').capitalize,
                 brand_info.css('a').attr('href').text]
    end
    brands
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SelectPhone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/phones/_finded_phones.html.erb
<tbody>
  <%- @phones.each do |phone|%>
    <tr>
      <th> <%= link_to phone[0], phone[1] %> </th>
      <td> <%= image_tag phone[2] %></td>
    </tr>
  <%end%>
</tbody>

app/views/phones/_form_models_for_select_ajax.html.haml
- unless @brand_models.blank?
  - @brand_models.each do |p|
    %option(value="#{p.last}")
      = p.first

app/views/phones/_table_with_phone_info.html.erb
<tbody>
  <%- @categories.count.times do |i|%>
    <%- @titles[i-1].count.times do |t_i|%>
      <tr>
        <th> <%= @titles[i-1][t_i-1]%> </th>
        <td> <%= @info[i-1][t_i-1]  %> </td>
      </tr>
    <%end%>
  <%end%>
</tbody>

app/views/phones/get_models_for_select.js.haml
- if @brand_models.blank?
  == $('.js-models').css({'display':'none'})
- else
  == var $element = $("#{j render('phones/form_models_for_select_ajax')}");
  == $('.js-models-label').slideDown();
  == $('#model').empty().append($element).slideDown();

app/views/phones/get_phone_info.js.haml
$('.phone_info').empty().append("#{j render('phones/table_with_phone_info')}").slideDown();

app/views/phones/search_phone.js.haml
$('.finded_phones').empty().append("#{j render('phones/finded_phones')}").slideDown();

app/views/phones/select_phone.html.erb
<h1> Choose phone </h1>
  <%= label_tag  'Brand:' %>
  <%= select_tag :brand, options_for_select(@brands), 
                          { class: 'form-control', 
                            data: {ajax_path: get_models_for_select_path}, 
                            prompt: "Choose brand of phone"} %>


  <%= label_tag  :model, 'Model:', class: 'js-models-label'%>
  <%= select_tag :model, options_for_select(@brand_models), 
                         { class: 'form-control js-models',
                           data: {ajax_path: get_phone_info_path}, 
                           prompt: "Choose model of phone"}%>
<br>

<table class="table table-bordered phone_info">
</table>

<br>

<div class="row">
  <%= form_tag search_phone_path, method: 'get', 
                                  id: "search_phone",
                                  class: 'input-group' do %>
    <%= text_field_tag :search, params[:search], { placeholder: 'Search for...',
                                                   class: "form-control js-search",
                                                   data: {ajax_path: search_phone_path}}%>
    <span class="input-group-btn">
      <%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
    </span>
  <% end %>
</div>

<table class="table table-bordered finded_phones">
</table>